In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('covid_toy.csv')

In [6]:
df.sample(5)

    age  gender  fever   cough       city has_covid
25   23    Male    NaN    Mild     Mumbai        No
11   65  Female   98.0    Mild     Mumbai       Yes
72   83  Female  101.0    Mild    Kolkata        No
57   49  Female   99.0  Strong  Bangalore        No
4    65  Female  101.0    Mild     Mumbai        No

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [10]:
display(X_train)

    age  gender  fever   cough       city
31   83    Male  103.0    Mild    Kolkata
32   34  Female  101.0  Strong      Delhi
19   42  Female    NaN  Strong  Bangalore
92   82  Female  102.0  Strong    Kolkata
52   47  Female  100.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
0    60    Male  103.0    Mild    Kolkata
14   51    Male  104.0    Mild  Bangalore
63   10    Male  100.0    Mild  Bangalore
38   49  Female  101.0    Mild      Delhi
86   25    Male  104.0    Mild  Bangalore

[80 rows x 5 columns]

Simple Imputer

In [11]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [12]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
display(X_train_fever)

array([[103.        ],
       [101.        ],
       [101.01369863],
       [102.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [ 99.        ],
       [101.01369863],
       [103.        ],
       [100.        ],
       [ 98.        ],
       [102.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [100.        ],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [102.        ],
       [101.        ],
       [101.        ],
       [ 99.        ],
       [104.        ],
       [102.        ],
       [103.        ],
       [104.        ],
       [103.        ],
       [100.        ],
       [104.        ],
       [100.        ],
       [101.01369863],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [101.01369863],
       [103.        ],
       [101.01369863],
       [102.        ],
       [100.        ],
       [101.        ],
       [101.01369863],
       [101.        ],
       [102.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [102.        ],
       [ 99.        ],
       [101.        ],
       [104.        ],
       [100.        ],
       [103.        ],
       [ 98.        ],
       [103.        ],
       [ 98.        ],
       [104.        ],
       [100.        ],
       [101.        ],
       [ 99.        ],
       [104.        ],
       [104.        ],
       [101.01369863],
       [ 98.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [104.        ],
       [100.        ],
       [101.        ],
       [104.        ]])

In [13]:
X_train_fever.shape

(80, 1)

One hot encoding

In [25]:
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

Ordinal Encoding

In [18]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

Now concatenate all the features

In [26]:
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values
X_train_age.shape

(80, 1)

In [29]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

In [32]:
X_train_transformed.shape

(80, 7)

Column Transform

In [33]:
from sklearn.compose import ColumnTransformer

In [35]:
transformer = ColumnTransformer(transformers = [
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough'
)

In [37]:
transformer.fit_transform(X_train).shape

(80, 7)

In [38]:
transformer.transform(X_test).shape

(20, 7)