KNN-imputation

In [21]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [22]:
df = pd.read_csv('train.csv',usecols=['Age','Pclass','Fare','Survived'])
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [23]:
df.isnull().mean() * 100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [24]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [25]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [26]:
X_train['Age_imputed'] = X_train['Age']
X_test['Age_imputed'] = X_test['Age']

X_test.sample(5)

     Pclass   Age     Fare  Age_imputed
830       3  15.0  14.4542         15.0
197       3  42.0   8.4042         42.0
236       2  44.0  26.0000         44.0
7         3   2.0  21.0750          2.0
813       3   6.0  31.2750          6.0

In [33]:
knn_imputer = KNNImputer(n_neighbors=5, weights='distance')
knn_imputer.fit(X_train)
X_train = knn_imputer.transform(X_train)
X_test = knn_imputer.transform(X_test)

In [34]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test,y_pred)

0.6983240223463687