In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Encoding used for categorical data

1)one-hot encoding
2)nominal encoding
3)ordinal encoding

nominal data -> each of them equal like : state names

ordinal data -> order wise : eg grades A , B , C

In [8]:
df = pd.read_csv('customer.csv')

In [10]:
df.sample(5)

    age  gender review education purchased
48   39  Female   Good        UG       Yes
11   74    Male   Good        UG       Yes
31   22  Female   Poor    School       Yes
12   51    Male   Poor    School        No
43   27    Male   Poor        PG        No

In [11]:
df = df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)
print(X_train.head())

     review education
35     Poor    School
8   Average        UG
47     Good        PG
15     Poor        UG
43     Poor        PG

**Ordinal Encoding**

In [13]:
from sklearn.preprocessing import OrdinalEncoder
o_e = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
o_e.fit(X_train)
X_train = o_e.transform(X_train)
X_test = o_e.transform(X_test)
X_train

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [0., 0.]])

In [14]:
o_e.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

**Label Encoding**

In [16]:
y_train.head()

35    Yes
8      No
47    Yes
15     No
43     No
Name: purchased, dtype: object

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
y_test = le.transform(y_test)
y_train

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1])